[package]
name = "proposer-builder-seperation"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
indicatif = "0.17.8"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.10.0"
serde = { version = "1.0.201", features = ["derive"] }

[profile.release]
debug = true
